/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutUnauthenticatedRouteImport } from './routes/_layout-unauthenticated'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout-authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUnauthenticatedTermsOfUseRouteImport } from './routes/_layout-unauthenticated/terms-of-use'
import { Route as LayoutUnauthenticatedPrivacyPolicyRouteImport } from './routes/_layout-unauthenticated/privacy-policy'
import { Route as LayoutUnauthenticatedHelloRouteImport } from './routes/_layout-unauthenticated/hello'
import { Route as LayoutAuthenticatedLayoutWorkspacesRouteImport } from './routes/_layout-authenticated/_layout-workspaces'
import { Route as LayoutAuthenticatedLayoutBoardRouteImport } from './routes/_layout-authenticated/_layout-board'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/index'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/settings'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnauthenticatedRoute = LayoutUnauthenticatedRouteImport.update({
  id: '/_layout-unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_layout-authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnauthenticatedTermsOfUseRoute =
  LayoutUnauthenticatedTermsOfUseRouteImport.update({
    id: '/terms-of-use',
    path: '/terms-of-use',
    getParentRoute: () => LayoutUnauthenticatedRoute,
  } as any)
const LayoutUnauthenticatedPrivacyPolicyRoute =
  LayoutUnauthenticatedPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => LayoutUnauthenticatedRoute,
  } as any)
const LayoutUnauthenticatedHelloRoute =
  LayoutUnauthenticatedHelloRouteImport.update({
    id: '/hello',
    path: '/hello',
    getParentRoute: () => LayoutUnauthenticatedRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesRoute =
  LayoutAuthenticatedLayoutWorkspacesRouteImport.update({
    id: '/_layout-workspaces',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedLayoutBoardRoute =
  LayoutAuthenticatedLayoutBoardRouteImport.update({
    id: '/_layout-board',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRouteImport.update(
    {
      id: '/workspaces/$workspaceId/settings',
      path: '/workspaces/$workspaceId/settings',
      getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRouteImport.update(
    {
      id: '/workspaces/$workspaceId/boards',
      path: '/workspaces/$workspaceId/boards',
      getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRouteImport.update(
    {
      id: '/workspaces/$workspaceId/billing',
      path: '/workspaces/$workspaceId/billing',
      getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRouteImport.update(
    {
      id: '/workspaces/$workspaceId/activity',
      path: '/workspaces/$workspaceId/activity',
      getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/hello': typeof LayoutUnauthenticatedHelloRoute
  '/privacy-policy': typeof LayoutUnauthenticatedPrivacyPolicyRoute
  '/terms-of-use': typeof LayoutUnauthenticatedTermsOfUseRoute
  '/workspaces': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  '/workspaces/$workspaceId/activity': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  '/workspaces/$workspaceId/billing': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  '/workspaces/$workspaceId/boards': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  '/workspaces/$workspaceId/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/hello': typeof LayoutUnauthenticatedHelloRoute
  '/privacy-policy': typeof LayoutUnauthenticatedPrivacyPolicyRoute
  '/terms-of-use': typeof LayoutUnauthenticatedTermsOfUseRoute
  '/workspaces': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  '/workspaces/$workspaceId/activity': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  '/workspaces/$workspaceId/billing': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  '/workspaces/$workspaceId/boards': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  '/workspaces/$workspaceId/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout-authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout-unauthenticated': typeof LayoutUnauthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_layout-authenticated/_layout-board': typeof LayoutAuthenticatedLayoutBoardRoute
  '/_layout-authenticated/_layout-workspaces': typeof LayoutAuthenticatedLayoutWorkspacesRouteWithChildren
  '/_layout-unauthenticated/hello': typeof LayoutUnauthenticatedHelloRoute
  '/_layout-unauthenticated/privacy-policy': typeof LayoutUnauthenticatedPrivacyPolicyRoute
  '/_layout-unauthenticated/terms-of-use': typeof LayoutUnauthenticatedTermsOfUseRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/hello'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/workspaces'
    | '/workspaces/$workspaceId/activity'
    | '/workspaces/$workspaceId/billing'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/hello'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/workspaces'
    | '/workspaces/$workspaceId/activity'
    | '/workspaces/$workspaceId/billing'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/settings'
  id:
    | '__root__'
    | '/'
    | '/_layout-authenticated'
    | '/_layout-unauthenticated'
    | '/login'
    | '/sign-up'
    | '/_layout-authenticated/_layout-board'
    | '/_layout-authenticated/_layout-workspaces'
    | '/_layout-unauthenticated/hello'
    | '/_layout-unauthenticated/privacy-policy'
    | '/_layout-unauthenticated/terms-of-use'
    | '/_layout-authenticated/_layout-workspaces/workspaces/'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutUnauthenticatedRoute: typeof LayoutUnauthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-unauthenticated': {
      id: '/_layout-unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutUnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-authenticated': {
      id: '/_layout-authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-unauthenticated/terms-of-use': {
      id: '/_layout-unauthenticated/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof LayoutUnauthenticatedTermsOfUseRouteImport
      parentRoute: typeof LayoutUnauthenticatedRoute
    }
    '/_layout-unauthenticated/privacy-policy': {
      id: '/_layout-unauthenticated/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutUnauthenticatedPrivacyPolicyRouteImport
      parentRoute: typeof LayoutUnauthenticatedRoute
    }
    '/_layout-unauthenticated/hello': {
      id: '/_layout-unauthenticated/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof LayoutUnauthenticatedHelloRouteImport
      parentRoute: typeof LayoutUnauthenticatedRoute
    }
    '/_layout-authenticated/_layout-workspaces': {
      id: '/_layout-authenticated/_layout-workspaces'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout-authenticated/_layout-board': {
      id: '/_layout-authenticated/_layout-board'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedLayoutBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/settings': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/settings'
      path: '/workspaces/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards'
      path: '/workspaces/$workspaceId/boards'
      fullPath: '/workspaces/$workspaceId/boards'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing'
      path: '/workspaces/$workspaceId/billing'
      fullPath: '/workspaces/$workspaceId/billing'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity'
      path: '/workspaces/$workspaceId/activity'
      fullPath: '/workspaces/$workspaceId/activity'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
  }
}

interface LayoutAuthenticatedLayoutWorkspacesRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute
}

const LayoutAuthenticatedLayoutWorkspacesRouteChildren: LayoutAuthenticatedLayoutWorkspacesRouteChildren =
  {
    LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdSettingsRoute,
  }

const LayoutAuthenticatedLayoutWorkspacesRouteWithChildren =
  LayoutAuthenticatedLayoutWorkspacesRoute._addFileChildren(
    LayoutAuthenticatedLayoutWorkspacesRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedLayoutBoardRoute: typeof LayoutAuthenticatedLayoutBoardRoute
  LayoutAuthenticatedLayoutWorkspacesRoute: typeof LayoutAuthenticatedLayoutWorkspacesRouteWithChildren
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedLayoutBoardRoute: LayoutAuthenticatedLayoutBoardRoute,
  LayoutAuthenticatedLayoutWorkspacesRoute:
    LayoutAuthenticatedLayoutWorkspacesRouteWithChildren,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutUnauthenticatedRouteChildren {
  LayoutUnauthenticatedHelloRoute: typeof LayoutUnauthenticatedHelloRoute
  LayoutUnauthenticatedPrivacyPolicyRoute: typeof LayoutUnauthenticatedPrivacyPolicyRoute
  LayoutUnauthenticatedTermsOfUseRoute: typeof LayoutUnauthenticatedTermsOfUseRoute
}

const LayoutUnauthenticatedRouteChildren: LayoutUnauthenticatedRouteChildren = {
  LayoutUnauthenticatedHelloRoute: LayoutUnauthenticatedHelloRoute,
  LayoutUnauthenticatedPrivacyPolicyRoute:
    LayoutUnauthenticatedPrivacyPolicyRoute,
  LayoutUnauthenticatedTermsOfUseRoute: LayoutUnauthenticatedTermsOfUseRoute,
}

const LayoutUnauthenticatedRouteWithChildren =
  LayoutUnauthenticatedRoute._addFileChildren(
    LayoutUnauthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutUnauthenticatedRoute: LayoutUnauthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
