/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutUnauthenticatedRouteImport } from './routes/_layout-unauthenticated'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout-authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUnauthenticatedTermsOfUseRouteImport } from './routes/_layout-unauthenticated/terms-of-use'
import { Route as LayoutUnauthenticatedPrivacyPolicyRouteImport } from './routes/_layout-unauthenticated/privacy-policy'
import { Route as LayoutUnauthenticatedHelloRouteImport } from './routes/_layout-unauthenticated/hello'
import { Route as LayoutAuthenticatedLayoutWorkspacesRouteImport } from './routes/_layout-authenticated/_layout-workspaces'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/index'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/index'
import { Route as LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRouteImport } from './routes/_layout-authenticated/workspaces.$workspaceId.boards.$boardId'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/index'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/settings'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/index'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/members'
import { Route as LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRouteImport } from './routes/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/invitations'

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteImport =
  createFileRoute(
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId',
  )()
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteImport =
  createFileRoute(
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings',
  )()

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnauthenticatedRoute = LayoutUnauthenticatedRouteImport.update({
  id: '/_layout-unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_layout-authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnauthenticatedTermsOfUseRoute =
  LayoutUnauthenticatedTermsOfUseRouteImport.update({
    id: '/terms-of-use',
    path: '/terms-of-use',
    getParentRoute: () => LayoutUnauthenticatedRoute,
  } as any)
const LayoutUnauthenticatedPrivacyPolicyRoute =
  LayoutUnauthenticatedPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => LayoutUnauthenticatedRoute,
  } as any)
const LayoutUnauthenticatedHelloRoute =
  LayoutUnauthenticatedHelloRouteImport.update({
    id: '/hello',
    path: '/hello',
    getParentRoute: () => LayoutUnauthenticatedRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesRoute =
  LayoutAuthenticatedLayoutWorkspacesRouteImport.update({
    id: '/_layout-workspaces',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => LayoutAuthenticatedLayoutWorkspacesRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute =
  LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRouteImport.update({
    id: '/workspaces/$workspaceId/boards/$boardId',
    path: '/workspaces/$workspaceId/boards/$boardId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRouteImport.update(
    {
      id: '/boards',
      path: '/boards',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRouteImport.update(
    {
      id: '/billing',
      path: '/billing',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRouteImport.update(
    {
      id: '/activity',
      path: '/activity',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteImport.update(
    {
      id: '/_layout-settings',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteImport.update(
    {
      id: '/_layout-members',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRouteImport.update(
    {
      id: '/members/',
      path: '/members/',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRouteImport.update(
    {
      id: '/members/members',
      path: '/members/members',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute,
    } as any,
  )
const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRouteImport.update(
    {
      id: '/members/invitations',
      path: '/members/invitations',
      getParentRoute: () =>
        LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/hello': typeof LayoutUnauthenticatedHelloRoute
  '/privacy-policy': typeof LayoutUnauthenticatedPrivacyPolicyRoute
  '/terms-of-use': typeof LayoutUnauthenticatedTermsOfUseRoute
  '/workspaces': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteWithChildren
  '/workspaces/$workspaceId/activity': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  '/workspaces/$workspaceId/billing': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  '/workspaces/$workspaceId/boards': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  '/workspaces/$workspaceId/boards/$boardId': typeof LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute
  '/workspaces/$workspaceId/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteWithChildren
  '/workspaces/$workspaceId/settings/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute
  '/workspaces/$workspaceId/settings/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute
  '/workspaces/$workspaceId/settings/members/invitations': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute
  '/workspaces/$workspaceId/settings/members/members': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute
  '/workspaces/$workspaceId/settings/members': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/hello': typeof LayoutUnauthenticatedHelloRoute
  '/privacy-policy': typeof LayoutUnauthenticatedPrivacyPolicyRoute
  '/terms-of-use': typeof LayoutUnauthenticatedTermsOfUseRoute
  '/workspaces': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/activity': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  '/workspaces/$workspaceId/billing': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  '/workspaces/$workspaceId/boards': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  '/workspaces/$workspaceId/boards/$boardId': typeof LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute
  '/workspaces/$workspaceId/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute
  '/workspaces/$workspaceId/settings/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute
  '/workspaces/$workspaceId/settings/members/invitations': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute
  '/workspaces/$workspaceId/settings/members/members': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute
  '/workspaces/$workspaceId/settings/members': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout-authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout-unauthenticated': typeof LayoutUnauthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_layout-authenticated/_layout-workspaces': typeof LayoutAuthenticatedLayoutWorkspacesRouteWithChildren
  '/_layout-unauthenticated/hello': typeof LayoutUnauthenticatedHelloRoute
  '/_layout-unauthenticated/privacy-policy': typeof LayoutUnauthenticatedPrivacyPolicyRoute
  '/_layout-unauthenticated/terms-of-use': typeof LayoutUnauthenticatedTermsOfUseRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteWithChildren
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteWithChildren
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  '/_layout-authenticated/workspaces/$workspaceId/boards/$boardId': typeof LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteWithChildren
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteWithChildren
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/settings': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/invitations': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/members': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute
  '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/': typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/hello'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/activity'
    | '/workspaces/$workspaceId/billing'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/boards/$boardId'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/settings/settings'
    | '/workspaces/$workspaceId/settings/'
    | '/workspaces/$workspaceId/settings/members/invitations'
    | '/workspaces/$workspaceId/settings/members/members'
    | '/workspaces/$workspaceId/settings/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/hello'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/activity'
    | '/workspaces/$workspaceId/billing'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/boards/$boardId'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/settings/settings'
    | '/workspaces/$workspaceId/settings/members/invitations'
    | '/workspaces/$workspaceId/settings/members/members'
    | '/workspaces/$workspaceId/settings/members'
  id:
    | '__root__'
    | '/'
    | '/_layout-authenticated'
    | '/_layout-unauthenticated'
    | '/login'
    | '/sign-up'
    | '/_layout-authenticated/_layout-workspaces'
    | '/_layout-unauthenticated/hello'
    | '/_layout-unauthenticated/privacy-policy'
    | '/_layout-unauthenticated/terms-of-use'
    | '/_layout-authenticated/_layout-workspaces/workspaces/'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards'
    | '/_layout-authenticated/workspaces/$workspaceId/boards/$boardId'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/settings'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/invitations'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/members'
    | '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutUnauthenticatedRoute: typeof LayoutUnauthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-unauthenticated': {
      id: '/_layout-unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutUnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-authenticated': {
      id: '/_layout-authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-unauthenticated/terms-of-use': {
      id: '/_layout-unauthenticated/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof LayoutUnauthenticatedTermsOfUseRouteImport
      parentRoute: typeof LayoutUnauthenticatedRoute
    }
    '/_layout-unauthenticated/privacy-policy': {
      id: '/_layout-unauthenticated/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutUnauthenticatedPrivacyPolicyRouteImport
      parentRoute: typeof LayoutUnauthenticatedRoute
    }
    '/_layout-unauthenticated/hello': {
      id: '/_layout-unauthenticated/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof LayoutUnauthenticatedHelloRouteImport
      parentRoute: typeof LayoutUnauthenticatedRoute
    }
    '/_layout-authenticated/_layout-workspaces': {
      id: '/_layout-authenticated/_layout-workspaces'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute
    }
    '/_layout-authenticated/workspaces/$workspaceId/boards/$boardId': {
      id: '/_layout-authenticated/workspaces/$workspaceId/boards/$boardId'
      path: '/workspaces/$workspaceId/boards/$boardId'
      fullPath: '/workspaces/$workspaceId/boards/$boardId'
      preLoaderRoute: typeof LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/boards'
      path: '/boards'
      fullPath: '/workspaces/$workspaceId/boards'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/billing'
      path: '/billing'
      fullPath: '/workspaces/$workspaceId/billing'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/activity'
      path: '/activity'
      fullPath: '/workspaces/$workspaceId/activity'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/settings': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings/settings'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/settings/members'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/members': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/members'
      path: '/members/members'
      fullPath: '/workspaces/$workspaceId/settings/members/members'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute
    }
    '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/invitations': {
      id: '/_layout-authenticated/_layout-workspaces/workspaces/$workspaceId/_layout-settings/settings/_layout-members/members/invitations'
      path: '/members/invitations'
      fullPath: '/workspaces/$workspaceId/settings/members/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute
    }
  }
}

interface LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute
}

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteChildren: LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteChildren =
  {
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersInvitationsRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersMembersRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersMembersIndexRoute,
  }

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteWithChildren =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute._addFileChildren(
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteChildren,
  )

interface LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteWithChildren
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute
}

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteChildren: LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteChildren =
  {
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsLayoutMembersRouteWithChildren,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsSettingsRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsIndexRoute,
  }

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteWithChildren =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute._addFileChildren(
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteChildren,
  )

interface LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteWithChildren
}

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteChildren: LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteChildren =
  {
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsSettingsRouteWithChildren,
  }

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteWithChildren =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRoute._addFileChildren(
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteChildren,
  )

interface LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteWithChildren
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute
}

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteChildren: LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteChildren =
  {
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdLayoutSettingsRouteWithChildren,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdActivityRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBillingRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdBoardsRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdIndexRoute,
  }

const LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteWithChildren =
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute._addFileChildren(
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteChildren,
  )

interface LayoutAuthenticatedLayoutWorkspacesRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute
  LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute: typeof LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteWithChildren
}

const LayoutAuthenticatedLayoutWorkspacesRouteChildren: LayoutAuthenticatedLayoutWorkspacesRouteChildren =
  {
    LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesIndexRoute,
    LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRoute:
      LayoutAuthenticatedLayoutWorkspacesWorkspacesWorkspaceIdRouteWithChildren,
  }

const LayoutAuthenticatedLayoutWorkspacesRouteWithChildren =
  LayoutAuthenticatedLayoutWorkspacesRoute._addFileChildren(
    LayoutAuthenticatedLayoutWorkspacesRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedLayoutWorkspacesRoute: typeof LayoutAuthenticatedLayoutWorkspacesRouteWithChildren
  LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute: typeof LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedLayoutWorkspacesRoute:
    LayoutAuthenticatedLayoutWorkspacesRouteWithChildren,
  LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute:
    LayoutAuthenticatedWorkspacesWorkspaceIdBoardsBoardIdRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutUnauthenticatedRouteChildren {
  LayoutUnauthenticatedHelloRoute: typeof LayoutUnauthenticatedHelloRoute
  LayoutUnauthenticatedPrivacyPolicyRoute: typeof LayoutUnauthenticatedPrivacyPolicyRoute
  LayoutUnauthenticatedTermsOfUseRoute: typeof LayoutUnauthenticatedTermsOfUseRoute
}

const LayoutUnauthenticatedRouteChildren: LayoutUnauthenticatedRouteChildren = {
  LayoutUnauthenticatedHelloRoute: LayoutUnauthenticatedHelloRoute,
  LayoutUnauthenticatedPrivacyPolicyRoute:
    LayoutUnauthenticatedPrivacyPolicyRoute,
  LayoutUnauthenticatedTermsOfUseRoute: LayoutUnauthenticatedTermsOfUseRoute,
}

const LayoutUnauthenticatedRouteWithChildren =
  LayoutUnauthenticatedRoute._addFileChildren(
    LayoutUnauthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutUnauthenticatedRoute: LayoutUnauthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
